# sudo chmod -R 755 /opt/docker_data/
# mkdir -p /opt/docker_data/wordpress/mysql_data
# mkdir -p /opt/docker_data/wordpress/wordpress

version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: wordpress-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - /opt/daocker_data/wordpress/mysql_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    restart: always
    container_name: wordpress
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    volumes:
      - /opt/daocker_data/wordpress/wordpress:/var/www/html
volumes:
  mysql_data:
  wordpress_data: